sudo: required
services: 
  - docker

before_install:
  - docker build -t christiancampos/docker-react -f Dockerfile.dev .

script:
  - docker run christiancampos/docker-react npm run test -- --coverage